name: Node.js Package

on:
  push:
    branches: [main]

jobs:
 build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: npm/action-setup@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install

  publish-npm-export:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: pnpm install
      - run: pnpm build
        working-directory: packages/feature/export/openapi

      - run: npm publish
        working-directory: packages/feature/export/openapi
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  # import
  publish-npm-import:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - run: pnpm install
      - run: pnpm build
        working-directory: packages/feature/import/openapi

      - run: npm publish
        working-directory: packages/feature/import/openapi
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - run: pnpm install
      - run: pnpm build
        working-directory: packages/feature/import/postman

      - run: npm publish
        working-directory: packages/feature/import/postman
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}




  publish-npm-push:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: pnpm install
      - run: pnpm build
        working-directory: packages/feature/push/eolink

      - run: npm publish
        working-directory: packages/feature/push/eolink
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
