name: Publish

on: [push]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout your updatd source code
    - uses: actions/checkout@v2

      # If the version has changed, create a new git tag for it.
    - name: build
      uses: actions/checkout@v2
      run: pnpm install
      run: pnpm build

      # Use this action to publish a single module to npm.
    - name: Publish
      if: success()
      uses: author/action-publish@stable
      env:
        REGISTRY_TOKEN: "${{ secrets.NPM_TOKEN }}"
